export const GUEST_CODES = {
  // 'code': { inviteType, maxGuests, full_name, phone_number, email }
  // inviteType: 'both' | 'event_1' (Indian) | 'event_2' (Western)

  // --- Sonia's guests ---
  'rk7x2p': { inviteType: 'both',    maxGuests: 1, full_name: 'Rita',           phone_number: '', email: '' },
  'bv3m9q': { inviteType: 'both',    maxGuests: 1, full_name: 'Bhavik',         phone_number: '', email: '' },
  'xb4wn8': { inviteType: 'event_1', maxGuests: 1, full_name: 'Ba',             phone_number: '', email: '' },
  'bh6rt5': { inviteType: 'both',    maxGuests: 2, full_name: 'Bharat',         phone_number: '', email: '' },
  'dy2k7f': { inviteType: 'both',    maxGuests: 2, full_name: 'Dhylon',         phone_number: '', email: '' },
  'kr9m4c': { inviteType: 'event_1', maxGuests: 2, full_name: 'Kiran',          phone_number: '', email: '' },
  'mn8p3v': { inviteType: 'event_1', maxGuests: 3, full_name: 'Manisha',        phone_number: '', email: '' },
  'nk5r7w': { inviteType: 'event_1', maxGuests: 3, full_name: 'Nikita',         phone_number: '', email: '' },
  'ch3b9x': { inviteType: 'event_1', maxGuests: 2, full_name: 'Chhaya',         phone_number: '', email: '' },
  'pm6kq2': { inviteType: 'event_1', maxGuests: 4, full_name: 'Prima',          phone_number: '', email: '' },
  'py4n8t': { inviteType: 'event_1', maxGuests: 4, full_name: 'Priya',          phone_number: '', email: '' },
  'dp7w3j': { inviteType: 'event_1', maxGuests: 4, full_name: 'Dipesh',         phone_number: '', email: '' },
  'rp2m6f': { inviteType: 'event_1', maxGuests: 2, full_name: 'Rupal',          phone_number: '', email: '' },
  'pn9k4c': { inviteType: 'event_1', maxGuests: 5, full_name: 'Poonam',         phone_number: '', email: '' },
  'sn5t8b': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sunil',          phone_number: '', email: '' },
  'sc3v7w': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sachita',        phone_number: '', email: '' },
  'vm8q2p': { inviteType: 'event_1', maxGuests: 4, full_name: 'Vimal',          phone_number: '', email: '' },
  'me6n4r': { inviteType: 'event_1', maxGuests: 1, full_name: 'Meena',          phone_number: '', email: '' },
  'rh4k9b': { inviteType: 'event_1', maxGuests: 3, full_name: 'Rekha',          phone_number: '', email: '' },
  'ds7r3w': { inviteType: 'event_1', maxGuests: 2, full_name: 'Deepa',          phone_number: '', email: '' },
  'sg2m8x': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sangeeta',       phone_number: '', email: '' },
  'bu9p5k': { inviteType: 'event_1', maxGuests: 1, full_name: 'Bhups',          phone_number: '', email: '' },
  'mj6w4n': { inviteType: 'event_1', maxGuests: 2, full_name: 'Manoj',          phone_number: '', email: '' },
  'mw3r9f': { inviteType: 'event_1', maxGuests: 2, full_name: 'Matthew',        phone_number: '', email: '' },
  'ka7n5b': { inviteType: 'both',    maxGuests: 2, full_name: 'Kareena',        phone_number: '', email: '' },
  'um4k2q': { inviteType: 'event_1', maxGuests: 3, full_name: 'Umesh',          phone_number: '', email: '' },
  'hm9r6p': { inviteType: 'both',    maxGuests: 2, full_name: 'Harman',         phone_number: '', email: '' },
  'ks5w3m': { inviteType: 'event_2', maxGuests: 1, full_name: 'Kishor',         phone_number: '', email: '' },
  'ay8b4n': { inviteType: 'both',    maxGuests: 1, full_name: 'Ayushi',         phone_number: '', email: '' },
  'ts2p7r': { inviteType: 'both',    maxGuests: 2, full_name: 'Tess',           phone_number: '', email: '' },
  'ad6k9m': { inviteType: 'both',    maxGuests: 1, full_name: 'Adina',          phone_number: '', email: '' },
  'gv3w5n': { inviteType: 'both',    maxGuests: 1, full_name: 'Gaavin',         phone_number: '', email: '' },
  'cr9b2k': { inviteType: 'event_2', maxGuests: 1, full_name: 'Carina',         phone_number: '', email: '' },
  'ur7m4p': { inviteType: 'both',    maxGuests: 1, full_name: 'Urvi',           phone_number: '', email: '' },
  'dk5r8w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Darshika',       phone_number: '', email: '' },
  'rt3n6b': { inviteType: 'both',    maxGuests: 2, full_name: 'Ritika',         phone_number: '', email: '' },
  'cy8k2v': { inviteType: 'both',    maxGuests: 2, full_name: 'Cindy',          phone_number: '', email: '' },
  'th4r7m': { inviteType: 'event_2', maxGuests: 2, full_name: 'Thea',           phone_number: '', email: '' },
  'jl9p5w': { inviteType: 'event_2', maxGuests: 2, full_name: 'Julian',         phone_number: '', email: '' },
  'sh2n8k': { inviteType: 'event_2', maxGuests: 1, full_name: 'Shayini',        phone_number: '', email: '' },
  'rb6w3r': { inviteType: 'event_2', maxGuests: 2, full_name: 'Rebecca',        phone_number: '', email: '' },
  'jo5m9p': { inviteType: 'event_2', maxGuests: 1, full_name: 'Joelle',         phone_number: '', email: '' },
  'gn7k4b': { inviteType: 'event_2', maxGuests: 1, full_name: 'Geno',           phone_number: '', email: '' },
  'ml3n8w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Melike',         phone_number: '', email: '' },
  'cm9p2r': { inviteType: 'event_2', maxGuests: 1, full_name: 'Carmen',         phone_number: '', email: '' },

  // --- Ishan's guests ---
  'kx4b7n': { inviteType: 'event_1', maxGuests: 2, full_name: 'Khushi Shingala', phone_number: '', email: '' },
  'pl8r3k': { inviteType: 'event_1', maxGuests: 2, full_name: 'Pallavi',         phone_number: '', email: '' },
  'bb6w9m': { inviteType: 'event_1', maxGuests: 2, full_name: 'Bobbie Sr.',       phone_number: '', email: '' },
  'bj3p5r': { inviteType: 'both',    maxGuests: 1, full_name: 'Bobbie Jr.',       phone_number: '', email: '' },
  'di9k7w': { inviteType: 'both',    maxGuests: 1, full_name: 'Deepa',            phone_number: '', email: '' },
  'rk2m4p': { inviteType: 'both',    maxGuests: 1, full_name: 'Rakesh',           phone_number: '', email: '' },
  'pr7n9b': { inviteType: 'both',    maxGuests: 2, full_name: 'Prerak',           phone_number: '', email: '' },
  'ut5w6k': { inviteType: 'event_1', maxGuests: 3, full_name: 'Utkarsh',          phone_number: '', email: '' },
  'ns4r8m': { inviteType: 'event_1', maxGuests: 3, full_name: 'Neeta Shukla',     phone_number: '', email: '' },
  'md9k3p': { inviteType: 'event_1', maxGuests: 5, full_name: 'Mukesh Dwivedi',   phone_number: '', email: '' },
  'st6n7w': { inviteType: 'event_1', maxGuests: 4, full_name: 'Sudha Tripathi',   phone_number: '', email: '' },
  'gm3r5b': { inviteType: 'event_1', maxGuests: 2, full_name: 'Guddu Mama',       phone_number: '', email: '' },
  'na8p2k': { inviteType: 'event_1', maxGuests: 1, full_name: 'Nana',             phone_number: '', email: '' },
  'ht4w9r': { inviteType: 'event_1', maxGuests: 1, full_name: 'Honey Tripathi',   phone_number: '', email: '' },
  'kn7m3p': { inviteType: 'both',    maxGuests: 1, full_name: 'Kangan',           phone_number: '', email: '' },
  'sa5k8n': { inviteType: 'both',    maxGuests: 2, full_name: 'Sunaabh',          phone_number: '', email: '' },
  'yo2r6w': { inviteType: 'both',    maxGuests: 1, full_name: 'Yogesh',           phone_number: '', email: '' },
  'hn9b4m': { inviteType: 'both',    maxGuests: 1, full_name: 'Henil',            phone_number: '', email: '' },
  'av6p7k': { inviteType: 'both',    maxGuests: 1, full_name: 'Ashvin',           phone_number: '', email: '' },
  'nl3w5r': { inviteType: 'both',    maxGuests: 1, full_name: 'Neelu',            phone_number: '', email: '' },
  'mg8k9p': { inviteType: 'both',    maxGuests: 1, full_name: 'Morgan',           phone_number: '', email: '' },
  'be4n3w': { inviteType: 'both',    maxGuests: 2, full_name: 'Beth',             phone_number: '', email: '' },
  'al7r2m': { inviteType: 'both',    maxGuests: 1, full_name: 'Alec',             phone_number: '', email: '' },
  'ki5p8b': { inviteType: 'both',    maxGuests: 1, full_name: 'Krishan',          phone_number: '', email: '' },
  'am9w4n': { inviteType: 'both',    maxGuests: 1, full_name: 'Amish',            phone_number: '', email: '' },
  'su3k7r': { inviteType: 'both',    maxGuests: 2, full_name: 'Sunny',            phone_number: '', email: '' },
  'at6m9p': { inviteType: 'event_1', maxGuests: 1, full_name: 'Adita',            phone_number: '', email: '' },
  'vn2r5k': { inviteType: 'event_2', maxGuests: 2, full_name: 'Vinay',            phone_number: '', email: '' },
  'ke8n3w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Keertan',          phone_number: '', email: '' },
  'sv5p7m': { inviteType: 'event_2', maxGuests: 1, full_name: 'Saavan',           phone_number: '', email: '' },

  // --- Test guests ---
  'test01': { inviteType: 'both',    maxGuests: 1, full_name: 'Test Solo Both',   phone_number: '', email: '' },
  'test02': { inviteType: 'both',    maxGuests: 5, full_name: 'Test Large Both',  phone_number: '', email: '' },
  'test03': { inviteType: 'event_1', maxGuests: 2, full_name: 'Test Indian Only', phone_number: '', email: '' },
  'test04': { inviteType: 'event_2', maxGuests: 3, full_name: 'Test Western Only', phone_number: '', email: '' },
  'test05': { inviteType: 'event_1', maxGuests: 1, full_name: 'Test Solo Indian', phone_number: '', email: '' },
}
