export const GUEST_CODES = {
  // 'code': { inviteType, maxGuests, full_name, invited_by, phone_number, email }
  // inviteType: 'both' | 'event_1' (Indian) | 'event_2' (Western)

  // --- Sonia's guests ---
  'rk7x2p': { inviteType: 'both',    maxGuests: 2, full_name: 'Rita & Bhavik Shah',                                        invited_by: 'Sonia', phone_number: '', email: '' },
  'xb4wn8': { inviteType: 'event_1', maxGuests: 1, full_name: 'Ba',                                          invited_by: 'Sonia', phone_number: '', email: '' },
  'bh6rt5': { inviteType: 'both',    maxGuests: 2, full_name: 'Bharat Shah & David Tyler',                        invited_by: 'Sonia', phone_number: '', email: '' },
  'dy2k7f': { inviteType: 'both',    maxGuests: 2, full_name: 'Dhylon Shah & Kezia Rosenberg',                    invited_by: 'Sonia', phone_number: '', email: '' },
  'kr9m4c': { inviteType: 'event_1', maxGuests: 2, full_name: 'Kiran & Meena Shah',                          invited_by: 'Sonia', phone_number: '', email: '' },
  'mn8p3v': { inviteType: 'event_1', maxGuests: 3, full_name: 'Manisha, Kavit & Manvi Shah',                 invited_by: 'Sonia', phone_number: '', email: '' },
  'nk5r7w': { inviteType: 'event_1', maxGuests: 3, full_name: 'Nikita, Tejas & Prem Solanki',             invited_by: 'Sonia', phone_number: '', email: '' },
  'ch3b9x': { inviteType: 'event_1', maxGuests: 2, full_name: 'Chhaya Shah & Yogesh Shah',                        invited_by: 'Sonia', phone_number: '', email: '' },
  'pm6kq2': { inviteType: 'event_1', maxGuests: 4, full_name: 'Prima Shah, Kumail Abdulhussein, Isabella & Sophia',                                       invited_by: 'Sonia', phone_number: '', email: '' },
  'py4n8t': { inviteType: 'event_1', maxGuests: 4, full_name: 'Priya, Katherine, Ronja & Eliah Behrens-Shah',     invited_by: 'Sonia', phone_number: '', email: '' },
  'dp7w3j': { inviteType: 'event_1', maxGuests: 4, full_name: 'Dipesh, Dipali, Aryan & Anya Shah',           invited_by: 'Sonia', phone_number: '', email: '' },
  'rp2m6f': { inviteType: 'event_1', maxGuests: 2, full_name: 'Rupal & Minal Shah',                          invited_by: 'Sonia', phone_number: '', email: '' },
  'pn9k4c': { inviteType: 'event_1', maxGuests: 5, full_name: 'Poonam Shah & family',                             invited_by: 'Sonia', phone_number: '', email: '' },
  'sn5t8b': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sunil & Geeta Shah',                          invited_by: 'Sonia', phone_number: '', email: '' },
  'sc3v7w': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sachita Shah & Akash Patel',                       invited_by: 'Sonia', phone_number: '', email: '' },
  'vm8q2p': { inviteType: 'event_1', maxGuests: 4, full_name: 'Vimal, Surbi, Neha & Ria Shah',               invited_by: 'Sonia', phone_number: '', email: '' },
  'me6n4r': { inviteType: 'event_1', maxGuests: 1, full_name: 'Mita Shah',                                        invited_by: 'Sonia', phone_number: '', email: '' },
  'rh4k9b': { inviteType: 'event_1', maxGuests: 3, full_name: 'Rekha, Mahendra & Minesh Mistry',           invited_by: 'Sonia', phone_number: '', email: '' },
  'ds7r3w': { inviteType: 'event_1', maxGuests: 2, full_name: 'Deepa & Rikesh Mistry',                     invited_by: 'Sonia', phone_number: '', email: '' },
  'sg2m8x': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sangeeta & Sunil Seeder',                   invited_by: 'Sonia', phone_number: '', email: '' },
  'bu9p5k': { inviteType: 'event_1', maxGuests: 2, full_name: 'Bhupinder Roopra & Cath Byrne',                    invited_by: 'Sonia', phone_number: '', email: '' },
  'mj6w4n': { inviteType: 'event_1', maxGuests: 2, full_name: 'Manoj & Mina Katri',                         invited_by: 'Sonia', phone_number: '', email: '' },
  'ka7n5b': { inviteType: 'both',    maxGuests: 2, full_name: 'Kareena Raichada & Sachin Patel',                  invited_by: 'Sonia', phone_number: '', email: '' },
  'um4k2q': { inviteType: 'event_1', maxGuests: 3, full_name: 'Umesh, Sushma & Karishma Raichada',       invited_by: 'Sonia', phone_number: '', email: '' },
  'hm9r6p': { inviteType: 'both',    maxGuests: 2, full_name: 'Harman Jabbal & Arjan Riat',                       invited_by: 'Sonia', phone_number: '', email: '' },
  'ks5w3m': { inviteType: 'event_2', maxGuests: 1, full_name: 'Kishor Sahadevan',                                 invited_by: 'Sonia', phone_number: '', email: '' },
  'ay8b4n': { inviteType: 'both',    maxGuests: 1, full_name: 'Ayushi Lanke',                                     invited_by: 'Sonia', phone_number: '', email: '' },
  'ts2p7r': { inviteType: 'both',    maxGuests: 2, full_name: 'Tess De Souza & Thomas Field',                        invited_by: 'Sonia', phone_number: '', email: '' },
  'ad6k9m': { inviteType: 'both',    maxGuests: 1, full_name: 'Adina Shafi',                                      invited_by: 'Sonia', phone_number: '', email: '' },
  'gv3w5n': { inviteType: 'both',    maxGuests: 1, full_name: 'Gaavin Vijeyacumaran',                             invited_by: 'Sonia', phone_number: '', email: '' },
  'cr9b2k': { inviteType: 'event_2', maxGuests: 1, full_name: 'Carina Narandralal',                               invited_by: 'Sonia', phone_number: '', email: '' },
  'ur7m4p': { inviteType: 'both',    maxGuests: 1, full_name: 'Urvi Sacicant',                                    invited_by: 'Sonia', phone_number: '', email: '' },
  'dk5r8w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Darshika Nanthakumar',                             invited_by: 'Sonia', phone_number: '', email: '' },
  'rt3n6b': { inviteType: 'both',    maxGuests: 2, full_name: 'Ritika Sehijpal & Yashaswi Gupta',                     invited_by: 'Sonia', phone_number: '', email: '' },
  'cy8k2v': { inviteType: 'both',    maxGuests: 2, full_name: 'Cindy Momodu & Collins Omokri',                    invited_by: 'Sonia', phone_number: '', email: '' },
  'th4r7m': { inviteType: 'event_2', maxGuests: 2, full_name: 'Thea Dyson & Kofi Larbi',                          invited_by: 'Sonia', phone_number: '', email: '' },
  'jl9p5w': { inviteType: 'event_2', maxGuests: 3, full_name: 'Julian Parmakov, Christina Petrova & Maya',        invited_by: 'Sonia', phone_number: '', email: '' },
  'sh2n8k': { inviteType: 'event_2', maxGuests: 1, full_name: 'Shayini Kugathas',                                 invited_by: 'Sonia', phone_number: '', email: '' },
  'rb6w3r': { inviteType: 'event_2', maxGuests: 2, full_name: 'Rebecca & Oliver Walker',                   invited_by: 'Sonia', phone_number: '', email: '' },
  'jo5m9p': { inviteType: 'event_2', maxGuests: 1, full_name: 'Joelle Hakim',                                     invited_by: 'Sonia', phone_number: '', email: '' },
  'gn7k4b': { inviteType: 'event_2', maxGuests: 1, full_name: 'Geno Racklin Asher',                               invited_by: 'Sonia', phone_number: '', email: '' },
  'ml3n8w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Melike Filizer',                                   invited_by: 'Sonia', phone_number: '', email: '' },
  'cm9p2r': { inviteType: 'event_2', maxGuests: 1, full_name: 'Carmen Meinson',                                           invited_by: 'Sonia', phone_number: '', email: '' },

  // --- Ishan's guests ---
  'kx4b7n': { inviteType: 'event_1', maxGuests: 2, full_name: 'Khushali Shingala & Niranjan Nampoothiri',                   invited_by: 'Ishan', phone_number: '', email: '' },
  'pl8r3k': { inviteType: 'event_1', maxGuests: 2, full_name: 'Pallavi Shingala & Kalpesh Shingala',                      invited_by: 'Ishan', phone_number: '', email: '' },
  'bb6w9m': { inviteType: 'event_1', maxGuests: 2, full_name: 'Sandeep Dubey & Neelam Dubey',                             invited_by: 'Ishan', phone_number: '', email: '' },
  'bj3p5r': { inviteType: 'both',    maxGuests: 1, full_name: 'Bobbie Dubey Jr.',                                 invited_by: 'Ishan', phone_number: '', email: '' },
  'di9k7w': { inviteType: 'both',    maxGuests: 2, full_name: 'Deepa & Rakesh Dwivedi',                                                      invited_by: 'Ishan', phone_number: '', email: '' },
  'pr7n9b': { inviteType: 'both',    maxGuests: 2, full_name: 'Prerak Dwivedi & Sonal Fotedar',                                              invited_by: 'Ishan', phone_number: '', email: '' },
  'ut5w6k': { inviteType: 'event_1', maxGuests: 3, full_name: 'Utkarsh, Bev, & Shiv Shukla',               invited_by: 'Ishan', phone_number: '', email: '' },
  'ns4r8m': { inviteType: 'event_1', maxGuests: 3, full_name: 'Neeta, Manoj & Amogh Shukla',                invited_by: 'Ishan', phone_number: '', email: '' },
  'md9k3p': { inviteType: 'event_1', maxGuests: 5, full_name: 'Mukesh, Archana, Manu, Aditya & Archit Dwivedi',      invited_by: 'Ishan', phone_number: '', email: '' },
  'st6n7w': { inviteType: 'event_1', maxGuests: 4, full_name: 'Sudha, Devindra, Shaleen & Sudeep Tripathi',    invited_by: 'Ishan', phone_number: '', email: '' },
  'gm3r5b': { inviteType: 'event_1', maxGuests: 2, full_name: 'Vijay & Rinku Dubey',                                 invited_by: 'Ishan', phone_number: '', email: '' },
  'na8p2k': { inviteType: 'event_1', maxGuests: 1, full_name: 'Nana',                                                    invited_by: 'Ishan', phone_number: '', email: '' },
  'ht4w9r': { inviteType: 'event_1', maxGuests: 3, full_name: 'Samir, Honey, & Param Tripathi',                                          invited_by: 'Ishan', phone_number: '', email: '' },
  'kn7m3p': { inviteType: 'both',    maxGuests: 1, full_name: 'Kangan Tripathi',                                         invited_by: 'Ishan', phone_number: '', email: '' },
  'sa5k8n': { inviteType: 'both',    maxGuests: 2, full_name: 'Sunaabh Trivedi & Isha Mati',                             invited_by: 'Ishan', phone_number: '', email: '' },
  'yo2r6w': { inviteType: 'both',    maxGuests: 1, full_name: 'Yogesh Patel',                                            invited_by: 'Ishan', phone_number: '', email: '' },
  'hn9b4m': { inviteType: 'both',    maxGuests: 1, full_name: 'Henil Premgi',                                            invited_by: 'Ishan', phone_number: '', email: '' },
  'av6p7k': { inviteType: 'both',    maxGuests: 1, full_name: 'Ashvin Mooruth',                                          invited_by: 'Ishan', phone_number: '', email: '' },
  'nl3w5r': { inviteType: 'both',    maxGuests: 1, full_name: 'Neelu Saraswatibhatla',                                   invited_by: 'Ishan', phone_number: '', email: '' },
  'mg8k9p': { inviteType: 'both',    maxGuests: 1, full_name: 'Morgan Saville',                                          invited_by: 'Ishan', phone_number: '', email: '' },
  'be4n3w': { inviteType: 'both',    maxGuests: 2, full_name: 'Bethany Bradley-Salmon & James Taylor',                   invited_by: 'Ishan', phone_number: '', email: '' },
  'al7r2m': { inviteType: 'both',    maxGuests: 1, full_name: 'Alexander Keir-Bucknall',                                      invited_by: 'Ishan', phone_number: '', email: '' },
  'ki5p8b': { inviteType: 'both',    maxGuests: 1, full_name: 'Krishan Sritharar',                                       invited_by: 'Ishan', phone_number: '', email: '' },
  'am9w4n': { inviteType: 'both',    maxGuests: 1, full_name: 'Amish Shah',                                              invited_by: 'Ishan', phone_number: '', email: '' },
  'su3k7r': { inviteType: 'both',    maxGuests: 2, full_name: 'Sunny Miglani & Akanksha Subramanian',                    invited_by: 'Ishan', phone_number: '', email: '' },
  'at6m9p': { inviteType: 'event_1', maxGuests: 1, full_name: 'Adita Tiwari',                                                   invited_by: 'Ishan', phone_number: '', email: '' },
  'vn2r5k': { inviteType: 'event_2', maxGuests: 2, full_name: 'Vinay Vekaria & Neha Shah',                               invited_by: 'Ishan', phone_number: '', email: '' },
  'ke8n3w': { inviteType: 'event_2', maxGuests: 1, full_name: 'Keertan Bhojani',                                         invited_by: 'Ishan', phone_number: '', email: '' },
  'sv5p7m': { inviteType: 'event_2', maxGuests: 1, full_name: 'Saavan Shah',                                             invited_by: 'Ishan', phone_number: '', email: '' },

  // --- Test guests ---
  'test01': { inviteType: 'both',    maxGuests: 1, full_name: 'Test Solo Both',    invited_by: 'Ishan', phone_number: '', email: '' },
  'test02': { inviteType: 'both',    maxGuests: 5, full_name: 'Test Large Both',   invited_by: 'Ishan', phone_number: '', email: '' },
  'test03': { inviteType: 'event_1', maxGuests: 2, full_name: 'Test Indian Only',  invited_by: 'Ishan', phone_number: '', email: '' },
  'test04': { inviteType: 'event_2', maxGuests: 3, full_name: 'Test Western Only', invited_by: 'Ishan', phone_number: '', email: '' },
  'test05': { inviteType: 'event_1', maxGuests: 1, full_name: 'Test Solo Indian',  invited_by: 'Ishan', phone_number: '', email: '' },
}
